using System;
using SkiaSharp;

namespace FramePFX.Editor {
    public static class TrackColours {
        private static readonly Random random = new Random();

        // A selection of track colours that work quite well with the light and dark themes
        private static readonly SKColor[] colours = {
            SKColors.BlueViolet,
            SKColors.Brown,
            SKColors.BurlyWood,
            SKColors.CadetBlue,
            SKColors.Chocolate,
            SKColors.Coral,
            SKColors.CornflowerBlue,
            SKColors.Crimson,
            SKColors.DarkBlue,
            SKColors.DarkCyan,
            SKColors.DarkGoldenrod,
            SKColors.DarkGray,
            SKColors.DarkGreen,
            SKColors.DarkKhaki,
            SKColors.DarkMagenta,
            SKColors.DarkOliveGreen,
            SKColors.DarkOrange,
            SKColors.DarkOrchid,
            SKColors.DarkRed,
            SKColors.DarkSalmon,
            SKColors.DarkSeaGreen,
            SKColors.DarkSlateBlue,
            SKColors.DarkSlateGray,
            SKColors.DarkTurquoise,
            SKColors.DarkViolet,
            SKColors.DeepPink,
            SKColors.DimGray,
            SKColors.DodgerBlue,
            SKColors.Firebrick,
            SKColors.ForestGreen,
            SKColors.Fuchsia,
            SKColors.Goldenrod,
            SKColors.Gray,
            SKColors.Green,
            SKColors.HotPink,
            SKColors.IndianRed,
            SKColors.Indigo,
            SKColors.LightBlue,
            SKColors.LightCoral,
            SKColors.LightSalmon,
            SKColors.LightSeaGreen,
            SKColors.LightSkyBlue,
            SKColors.LightSlateGray,
            SKColors.LightSteelBlue,
            SKColors.Magenta,
            SKColors.Maroon,
            SKColors.MediumBlue,
            SKColors.MediumOrchid,
            SKColors.MediumPurple,
            SKColors.MediumSeaGreen,
            SKColors.MediumSlateBlue,
            SKColors.MediumVioletRed,
            SKColors.MidnightBlue,
            SKColors.Navy,
            SKColors.Olive,
            SKColors.OliveDrab,
            SKColors.Orange,
            SKColors.OrangeRed,
            SKColors.Orchid,
            SKColors.PaleVioletRed,
            SKColors.Peru,
            SKColors.Pink,
            SKColors.Plum,
            SKColors.PowderBlue,
            SKColors.Purple,
            SKColors.RosyBrown,
            SKColors.RoyalBlue,
            SKColors.SaddleBrown,
            SKColors.SandyBrown,
            SKColors.SeaGreen,
            SKColors.Sienna,
            SKColors.SkyBlue,
            SKColors.SlateBlue,
            SKColors.SlateGray,
            SKColors.SteelBlue,
            SKColors.Tan,
            SKColors.Teal,
            SKColors.Tomato,
            SKColors.Violet,
            SKColors.YellowGreen,
        };

        public static SKColor GetRandomColour() {
            return colours[random.Next(0, colours.Length)];
        }
    }
}